# User root password root
version: '3.1'

services:
  db:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: "${DBPASS}"
      POSTGRES_DB: "${DBNAME}"
      POSTGRES_USER: "${DBUSER}"
    ports:
      - '5432:5432'
    expose: 
      - '5432'