"""empty message

Revision ID: 51b1cbc4f02b
Revises: 0a4a5cc4832e
Create Date: 2020-05-08 12:38:19.467062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51b1cbc4f02b'
down_revision = '0a4a5cc4832e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'category_id')
    # ### end Alembic commands ###
