"""empty message

Revision ID: 70c45d55b37b
Revises: c026109e0c4b
Create Date: 2020-05-10 12:50:40.083360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70c45d55b37b'
down_revision = 'c026109e0c4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'books', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.alter_column('books', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
